// Curated list of well-known global motorcycle manufacturers and their more
// popular current/recent models. Model names for US-market brands were
// cross-checked against NHTSA's public vPIC vehicle database (real current
// lineups, not guessed) — brands NHTSA has little or no data for (mostly
// ones not officially sold in the US) fall back to a best-effort manual
// list instead. Either way this is a curated shortlist, not an exhaustive
// database — anything not covered here falls through to "Other" in the bike
// form, which accepts free text instead.
//
// Order is intentional, not alphabetical: the first POPULAR_MAKE_COUNT
// entries are shown as a separate "Popular" group ahead of the rest, ranked
// by roughly a blend of global sales volume and brand recognition.
export const POPULAR_MAKE_COUNT = 10;

export const MOTORCYCLE_BRANDS: { make: string; models: string[] }[] = [
  {
    make: 'Honda',
    models: [
      'CB300R',
      'CB500F',
      'CB500X',
      'CB650R',
      'CB1000R',
      'CBR300R',
      'CBR500R',
      'CBR600RR',
      'CBR650R',
      'CBR1000RR',
      'Africa Twin',
      'Africa Twin Adventure Sports',
      'Gold Wing',
      'Rebel 300',
      'Rebel 500',
      'Rebel 1100',
      'Shadow',
      'Grom',
      'ADV150',
      'PCX150',
    ],
  },
  {
    make: 'Yamaha',
    models: [
      'MT-03',
      'MT-07',
      'MT-09',
      'MT-10',
      'YZF-R3',
      'YZF-R6',
      'YZF-R7',
      'YZF-R1',
      'Tenere 700',
      'Super Tenere',
      'Bolt',
      'XSR900',
      'TW200',
    ],
  },
  {
    make: 'Kawasaki',
    models: [
      'Ninja 400',
      'Ninja 650',
      'Ninja ZX-6R',
      'Ninja ZX-10R',
      'Z650',
      'Z900',
      'Versys 650',
      'Vulcan S',
      'KLR650',
    ],
  },
  {
    make: 'Suzuki',
    models: [
      'GSX-8S',
      'GSX-R600',
      'GSX-R750',
      'GSX-R1000',
      'GSX-S1000',
      'SV650',
      'Hayabusa',
      'V-Strom 650',
      'V-Strom 1050',
      'Boulevard',
      'Katana 1000',
    ],
  },
  {
    make: 'Harley-Davidson',
    models: [
      'Iron 883',
      'Nightster',
      'Nightster Special',
      'Sportster S',
      'Pan America',
      'Pan America Special',
      'Fat Bob 114',
      'Fat Boy',
      'Fat Boy 114',
      'Low Rider S',
      'Low Rider ST',
      'Heritage Classic',
      'Breakout',
      'Road King',
      'Road Glide',
      'Street Glide',
    ],
  },
  {
    make: 'Ducati',
    models: [
      'Monster',
      'Panigale V2',
      'Panigale V4',
      'Multistrada',
      'Scrambler',
      'Diavel / XDiavel',
      'Streetfighter',
      'Desert X',
      'Hypermotard',
      'SuperSport',
    ],
  },
  {
    make: 'BMW Motorrad',
    models: [
      'R 1250 GS',
      'F 850 GS',
      'F 750 GS',
      'S 1000 RR',
      'S 1000 R',
      'R nineT',
      'G 310 R',
      'G 310 GS',
      'K 1600 GT',
      'R 18',
      'CE 04',
    ],
  },
  {
    make: 'Triumph',
    models: [
      'Trident 660',
      'Street Twin',
      'Street Scrambler',
      'Street Triple R',
      'Street Triple RS',
      'Speed Twin',
      'Speed Twin 900',
      'Speed Triple 1200 RS',
      'Speed Triple 1200 RR',
      'Tiger 900',
      'Tiger 900 GT',
      'Tiger 900 Rally',
      'Tiger 1200 GT',
      'Tiger 1200 Rally',
      'Scrambler 900',
      'Scrambler 1200 XE',
      'Scrambler 1200 XC',
      'Bonneville T100',
      'Bonneville T120',
      'Bonneville Speedmaster',
      'Bonneville Bobber',
      'Thruxton RS',
      'Rocket 3 GT',
      'Rocket 3 R',
    ],
  },
  {
    make: 'KTM',
    models: [
      'Duke 390',
      'Duke 790',
      'Duke 890',
      'RC 390',
      '690 Duke',
      '690 Enduro',
      '790 Adventure',
      '890 Adventure',
      '1290 Super Adventure',
    ],
  },
  {
    make: 'Royal Enfield',
    models: [
      'Bullet 350',
      'Classic 350',
      'Meteor 350',
      'Hunter 350',
      'Himalayan 411',
      'Interceptor 650',
      'Continental GT 650',
    ],
  },
  {
    make: 'Indian Motorcycle',
    models: [
      'Scout',
      'Chief',
      'Chief Bobber',
      'Chief Dark Horse',
      'Chieftain',
      'Chieftain Dark Horse',
      'Chieftain Limited',
      'Springfield',
      'Roadmaster',
      'FTR',
      'Challenger',
      'Pursuit',
    ],
  },
  { make: 'Aprilia', models: ['RS 660', 'Tuono 660', 'RSV4', 'Tuareg 660'] },
  { make: 'Moto Guzzi', models: ['V7', 'V7 Stone', 'V7 Special', 'V85 TT', 'V100 Mandello', 'V9 Bobber'] },
  { make: 'Vespa', models: ['Primavera', 'Sprint', 'GTS 300', 'Elettrica', '946'] },
  {
    make: 'Husqvarna',
    models: ['Svartpilen 401', 'Svartpilen 701', 'Vitpilen 401', 'Norden 901', '701 Enduro', '701 Supermoto'],
  },
  { make: 'Benelli', models: ['TRK 502', 'Leoncino 500', 'Imperiale 400', 'TNT 600'] },
  { make: 'CFMoto', models: ['300NK', '300SS', '450SS', '650NK', '650 ADVentura', '700CL-X', '800NK'] },
  { make: 'Zero Motorcycles', models: ['S', 'SR', 'SR/F', 'SR/S', 'DS', 'DSR', 'DSR/X', 'FXE'] },
  { make: 'Can-Am', models: ['Ryker', 'Spyder'] },
  { make: 'Hero MotoCorp', models: ['Splendor', 'Xtreme 160R', 'XPulse 200'] },
  { make: 'Bajaj', models: ['Pulsar', 'Dominar', 'Avenger'] },
  { make: 'TVS', models: ['Apache RTR', 'Ronin'] },
  { make: 'Kymco', models: ['Xciting 400', 'Like 150'] },
  { make: 'Norton', models: ['Commando 961'] },
  { make: 'MV Agusta', models: ['Brutale', 'Dragster', 'F3', 'Superveloce', 'Turismo Veloce'] },
  { make: 'Ural', models: ['Gear Up', 'Patrol', 'cT'] },
];

export const OTHER_OPTION = 'Other';
